GET http://localhost:3001/brawlers HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/brawlers HTTP/1.1
Content-Type: application/json

{
    "name": "Frank"
}

###

PUT http://localhost:3001/brawlers/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Rico"
}